### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by TheFallStar** [tigerAndBull/LoadAnimatedDemo-ios#1]
说实话，过渡动画制作水准很高，但不太符合集成的一些通用原则。最重要的还是无侵入性、组件化程度要高。直白一点就是列表的过渡动画都有了为什么没有通用的UIView加载的动画？另外控件的最高水准就是无侵入性，也就是项目代码不需任何修改，只要引入头文件就直接发挥作用了。希望您能加以进阶和修改。当然写了总比不写好，像我自知水平有限，所以就干脆什么也不写了，直接找别人的用。😀

**Comment by tigerAndBull** [comment]
你好，你的这个侵入式的思想，也是非常我想遵循的。但是有些必要的操作，我的初衷是希望程序员自己去设置，我并不能无脑地将所有组件都动，而且我不能智能地去判断哪个控件需要动，因为它是无规律的。谢谢你的建议，之前有人在简书提到导入头文件就发挥作用，我还要考虑一下！UIView的加载动画在实际操作中存在着问题，这个我也是首先尝试的，后面会持续更新，希望多多关注！

**Comment by tigerAndBull** [comment]
> 说实话，过渡动画制作水准很高，但不太符合集成的一些通用原则。最重要的还是无侵入性、组件化程度要高。直白一点就是列表的过渡动画都有了为什么没有通用的UIView加载的动画？另外控件的最高水准就是无侵入性，也就是项目代码不需任何修改，只要引入头文件就直接发挥作用了。希望您能加以进阶和修改。当然写了总比不写好，像我自知水平有限，所以就干脆什么也不写了，直接找别人的用。😀

你好，你的这个侵入式的思想，也是非常我想遵循的。但是有些必要的操作，我的初衷是希望程序员自己去设置，我并不能无脑地将所有组件都动，而且我不能智能地去判断哪个控件需要动，因为它是无规律的。谢谢你的建议，之前有人在简书提到导入头文件就发挥作用，我还要考虑一下！UIView的加载动画在实际操作中存在着问题，这个我也是首先尝试的，后面会持续更新，希望多多关注！

**Comment by tigerAndBull** [comment]
> 说实话，过渡动画制作水准很高，但不太符合集成的一些通用原则。最重要的还是无侵入性、组件化程度要高。直白一点就是列表的过渡动画都有了为什么没有通用的UIView加载的动画？另外控件的最高水准就是无侵入性，也就是项目代码不需任何修改，只要引入头文件就直接发挥作用了。希望您能加以进阶和修改。当然写了总比不写好，像我自知水平有限，所以就干脆什么也不写了，直接找别人的用。😀

我想了一下，可以全局注册组件，后面会更新，谢谢您的建议。

**Comment by tigerAndBull** [comment]
> 说实话，过渡动画制作水准很高，但不太符合集成的一些通用原则。最重要的还是无侵入性、组件化程度要高。直白一点就是列表的过渡动画都有了为什么没有通用的UIView加载的动画？另外控件的最高水准就是无侵入性，也就是项目代码不需任何修改，只要引入头文件就直接发挥作用了。希望您能加以进阶和修改。当然写了总比不写好，像我自知水平有限，所以就干脆什么也不写了，直接找别人的用。😀

况且我是不需要动源代码的，只需要注册，注册～～，我再想想其他好方法！

**Comment by tigerAndBull** [comment]
> 说实话，过渡动画制作水准很高，但不太符合集成的一些通用原则。最重要的还是无侵入性、组件化程度要高。直白一点就是列表的过渡动画都有了为什么没有通用的UIView加载的动画？另外控件的最高水准就是无侵入性，也就是项目代码不需任何修改，只要引入头文件就直接发挥作用了。希望您能加以进阶和修改。当然写了总比不写好，像我自知水平有限，所以就干脆什么也不写了，直接找别人的用。😀

刚刚你说的UIView的动画我理解错了，会持续更新常用的组件，请持续关注！

**Comment by tigerAndBull** [comment]
> 说实话，过渡动画制作水准很高，但不太符合集成的一些通用原则。最重要的还是无侵入性、组件化程度要高。直白一点就是列表的过渡动画都有了为什么没有通用的UIView加载的动画？另外控件的最高水准就是无侵入性，也就是项目代码不需任何修改，只要引入头文件就直接发挥作用了。希望您能加以进阶和修改。当然写了总比不写好，像我自知水平有限，所以就干脆什么也不写了，直接找别人的用。😀

已经进行了更新！
