### ISSUE TITLE
TableViewCell中子控件什么都没设置，但是全部都有动画

### ISSUE THREAD

**Issue by kzq5** [tigerAndBull/LoadAnimatedDemo-ios#11]
只设置了这个全局设置：
    [[TABViewAnimated sharedAnimated]initWithShimmerAnimated];
    [TABViewAnimated sharedAnimated].animatedColor = tab_kBackColor;
以及TableView的这个属性：
_tableView.animatedStyle = TABTableViewAnimationStart;  // 开启动画

**Comment by tigerAndBull** [comment]
> 只设置了这个全局设置：
> [[TABViewAnimated sharedAnimated]initWithShimmerAnimated];
> [TABViewAnimated sharedAnimated].animatedColor = tab_kBackColor;
> 以及TableView的这个属性：
> _tableView.animatedStyle = TABTableViewAnimationStart; // 开启动画

这样是正确的，“initWithShimmerAnimated” 你选择了全局闪光灯模式，只要开启动画，那么所有子控件都将有动画
