### ISSUE TITLE
如何部分view做动画显示

### ISSUE THREAD

**Issue by MuRanJiangXia** [tigerAndBull/LoadAnimatedDemo-ios#13]
在cell 上有的时候 需要显示一些 view 怎么能逃离 这个动画呀，有的view不想显示出来

**Comment by MuRanJiangXia** [comment]
~

**Comment by tigerAndBull** [comment]
> 在cell 上有的时候 需要显示一些 view 怎么能逃离 这个动画呀，有的view不想显示出来

使用`Default Animation`目录下的初始化方法

**Comment by MuRanJiangXia** [comment]
需要在这个类 TABViewAnimated 中自己写么？

**Comment by tigerAndBull** [comment]
如果你使用了`- (void)initWithShimmerAnimated`或者`- (void)initWithOnlySkeleton`
当前版本会默认选中所有view。



目前的解决方案：
在appDelegate初始化的时候选择
`- (void)initWithDefaultAnimated`或者 `- (void)initWithCustomAnimation`方法，
然后
再订制你需要的动画，不需要动的动画则不需要做任何操作。


如果取消选中很有必要，你再联系我，会尽早进行优化。


 



------------------ 原始邮件 ------------------
发件人: "Cyan"<notifications@github.com>;
发送时间: 2019年2月12日(星期二) 上午10:01
收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] 如何部分view做动画显示 (#13)




需要在这个类 TABViewAnimated 中自己写么？
