### ISSUE TITLE
我在tableView初始化的时候开启了动画，但是我运行的时候我感觉加载顺序是先加载我cell上的控件，并且把控件上的内容也加载出来了，然后才会出现你框架的骨架然后再是网络请请求成功刷新数据源

### ISSUE THREAD

**Issue by ryanranya** [tigerAndBull/LoadAnimatedDemo-ios#17]

**Comment by ryanranya** [comment]
我在tableView初始化的时候开启了动画，但是我运行的时候我感觉加载顺序是先加载我cell上的控件，并且把控件上的内容也加载出来了，然后才会出现你框架的骨架然后再是网络请请求成功刷新数据源

**Comment by CCYSmile** [comment]
// 在加载动画的时候，即未获得数据时，不要走加载控件数据的方法
    if (self.mainTV.animatedStyle != TABTableViewAnimationStart) {
        [cell initWithData:dataArray[indexPath.row]];
    }
我在看 demo 里面有这样处理加载 cell上的控件，不知道对你有没有帮助

**Comment by tigerAndBull** [comment]
楼上回复的是正确的，
目前框架体系下，这个地方耦合度比较高

**Comment by tigerAndBull** [comment]
1.9以后的版本不再有这种耦合。
