### ISSUE TITLE
框架写得不错！补充两个问题，相信大多数人都会遇到

### ISSUE THREAD

**Issue by 91renb** [tigerAndBull/LoadAnimatedDemo-ios#3]
问题1：设置tableView代理时，如果先设置_tableView.dataSource = self;再设置_tableView.delegate = self;不会出现动画效果；（作者的框架必须是要先delegate，再设置dataSource，才会出现动画效果），希望可以优化一下。
问题2：希望可以设置对tableView多分区的支持，比如我做了如下修改：
![image](https://user-images.githubusercontent.com/23326671/47547850-a3375880-d929-11e8-9977-90e60fefc020.png)
![image](https://user-images.githubusercontent.com/23326671/47547904-d2e66080-d929-11e8-8487-864e4d3c7589.png)

**Comment by tigerAndBull** [comment]
> 问题1：设置tableView代理时，如果先设置_tableView.dataSource = self;再设置_tableView.delegate = self;不会出现动画效果；（作者的框架必须是要先delegate，再设置dataSource，才会出现动画效果），希望可以优化一下。
> 问题2：希望可以设置对tableView多分区的支持，比如我做了如下修改：
> ![image](https://user-images.githubusercontent.com/23326671/47547850-a3375880-d929-11e8-9977-90e60fefc020.png)
> ![image](https://user-images.githubusercontent.com/23326671/47547904-d2e66080-d929-11e8-8487-864e4d3c7589.png)

会持续优化，目前pod最新1.4.0，建议使用最新，向下兼容

**Comment by 91renb** [comment]
好的，挺你！

**Comment by 91renb** [comment]
你这个框架在iOS9系统上不能使用吧，坑很多，集成到项目中，引起各种闪退，监听键盘输入时就引起闪退，希望好好优化一下，提高兼容性。我线上的项目又得紧急重新发版😌

**Comment by tigerAndBull** [comment]
> 你这个框架在iOS9系统上不能使用吧，坑很多，集成到项目中，引起各种闪退，监听键盘输入时就引起闪退，希望好好优化一下，提高兼容性。我线上的项目又得紧急重新发版😌

崩溃问题是否是所有系统都会存在的？

**Comment by 91renb** [comment]
只是部分系统才有的，要真机调试。iOS9系统出现的最多，在iOS10之前的系统tableView也是没有动画效果。你可以测试一下，当项目中有输入框进入编辑状态时，键盘输入会引起闪退。

**Comment by tigerAndBull** [comment]
> 只是部分系统才有的，要真机调试。iOS9系统出现的最多，在iOS10之前的系统tableView也是没有动画效果。

哈哈 crash log有吗，可能和我最近发现的问题有关

**Comment by 91renb** [comment]
在iOS10.3以下的系统tableView还是没有动画，你可以对低版本做一下兼容

**Comment by tigerAndBull** [comment]
目前我还不知道是何原因引起，重点是我没有10.3以下的系统
------------------ 原始邮件 ------------------
发件人: "任波"<notifications@github.com>;
发送时间: 2018年11月14日(星期三) 中午1:57
收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] 框架写得不错！补充两个问题，相信大多数人都会遇到 (#3)




在iOS10.3以下的系统tableView还是没有动画，你可以对低版本做一下兼容

**Comment by tigerAndBull** [comment]
> 目前我还不知道是何原因引起，重点是我没有10.3以下的系统 ------------------ 原始邮件 ------------------ 发件人: "任波"<notifications@github.com>; 发送时间: 2018年11月14日(星期三) 中午1:57 收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>; 抄送: "安文虎"<1429299849@qq.com>; "Comment"<comment@noreply.github.com>; 主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] 框架写得不错！补充两个问题，相信大多数人都会遇到 (#3) 在iOS10.3以下的系统tableView还是没有动画，你可以对低版本做一下兼容 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

已解决self.delegate和self.dataSource优先级问题

**Comment by tigerAndBull** [comment]
> 好的

低版本无动画问题已经解决！
