### ISSUE TITLE
iOS10.1上 tableView会直接不显示

### ISSUE THREAD

**Issue by hubin97** [tigerAndBull/LoadAnimatedDemo-ios#4]
iOS10.1上 tableView会直接不显示

**Comment by tigerAndBull** [comment]
> iOS10.1上 tableView会直接不显示

你好，已经解决！

**Comment by hubin97** [comment]
优秀!

**Comment by hubin97** [comment]
试了下, 在cell.xib上面放置imageView,label; 发现imageview有动画, label没有

**Comment by tigerAndBull** [comment]
请确认你的使用方式，我demo里就是label




------------------ 原始邮件 ------------------
发件人: "Hubin_Huang"<notifications@github.com>;
发送时间: 2018年11月27日(星期二) 上午9:44
收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] iOS10.1上 tableView会直接不显示 (#4)




试了下, 在cell.xib上面放置imageView,label; 发现imageview有动画, label没有
