### ISSUE TITLE
cell上的按钮,如果是自定义按钮,比如调整UIEdgeInsets(图片在左，文字在右等)，会有问题

### ISSUE THREAD

**Issue by lzc1022** [tigerAndBull/LoadAnimatedDemo-ios#6]

**Comment by tigerAndBull** [comment]
> _No description provided._

之前没有考虑这个，后续修复～

**Comment by lzc1022** [comment]
![00974bf4-eb80-49d8-8363-720d698e995b](https://user-images.githubusercontent.com/9947322/49192261-452ce380-f3b5-11e8-81ef-c1578363a54d.png)
![d1fe4184-8927-41e0-8f5c-e3060a48f3ed](https://user-images.githubusercontent.com/9947322/49192262-452ce380-f3b5-11e8-97df-ba4202bbdbc6.png)
[fd.zip](https://github.com/tigerAndBull/LoadAnimatedDemo-ios/files/2627160/fd.zip)
如上图：(PS：能否再加个方法，就想调用initWithShimmerAnimated一样，快捷调用另一种动画效果)

**Comment by tigerAndBull** [comment]
> ![00974bf4-eb80-49d8-8363-720d698e995b](https://user-images.githubusercontent.com/9947322/49192261-452ce380-f3b5-11e8-81ef-c1578363a54d.png)
> ![d1fe4184-8927-41e0-8f5c-e3060a48f3ed](https://user-images.githubusercontent.com/9947322/49192262-452ce380-f3b5-11e8-97df-ba4202bbdbc6.png)
> [fd.zip](https://github.com/tigerAndBull/LoadAnimatedDemo-ios/files/2627160/fd.zip)
> 如上图：(PS：能否再加个方法，就想调用initWithShimmerAnimated一样，快捷调用另一种动画效果)

初始化 有默认参数的，你先找一下宏定义吧

**Comment by tigerAndBull** [comment]
可以，加




------------------ 原始邮件 ------------------
发件人: "李哥"<notifications@github.com>;
发送时间: 2018年11月29日(星期四) 中午11:29
收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] cell上的按钮,如果是自定义按钮,比如调整UIEdgeInsets(图片在左，文字在右等)，会有问题 (#6)




闪光灯模式下, 无需为子组件设置动画类型, 父组件开启动画，所有子组件都会设置为TABViewLoadAnimationWithOnlySkeleton(经典动画能否也加个类似的属性，所有子组件不用设置)

**Comment by tigerAndBull** [comment]
[[TABViewAnimated sharedAnimated] initWithAnimatedDuration:0.5 withColor:tab_kBackColor];





------------------ 原始邮件 ------------------
发件人: "李哥"<notifications@github.com>;
发送时间: 2018年11月29日(星期四) 中午11:29
收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] cell上的按钮,如果是自定义按钮,比如调整UIEdgeInsets(图片在左，文字在右等)，会有问题 (#6)




闪光灯模式下, 无需为子组件设置动画类型, 父组件开启动画，所有子组件都会设置为TABViewLoadAnimationWithOnlySkeleton(经典动画能否也加个类似的属性，所有子组件不用设置)

**Comment by lzc1022** [comment]
![d7649ee9-9c5b-45d3-8d96-59e43d5c1da0](https://user-images.githubusercontent.com/9947322/49201217-03169880-f3db-11e8-8bf2-d35d6504d548.png)
![e7c27b0f-bb74-4a96-8aa2-b81bfde3f338](https://user-images.githubusercontent.com/9947322/49201223-04e05c00-f3db-11e8-9a01-d429741f35ea.png)
这样设置不会出现默认动画,如果Appdete设置闪光,cell里面也注释掉，就可以显示动画，但是默认动画不行

**Comment by tigerAndBull** [comment]
是的，没有这种设定




------------------ 原始邮件 ------------------
发件人: "李哥"<notifications@github.com>;
发送时间: 2018年11月29日(星期四) 中午1:32
收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] cell上的按钮,如果是自定义按钮,比如调整UIEdgeInsets(图片在左，文字在右等)，会有问题 (#6)





 
 这样设置不会出现默认动画,如果Appdete设置闪光,cell里面也注释掉，就可以显示动画，但是默认动画不行

**Comment by lzc1022** [comment]
能否加个属性和闪光模式一样,另外我提供的Demo如果不加闪光动画，布局没有错，加了动画就会出错，希望作者能指出问题所在，谢谢

**Comment by tigerAndBull** [comment]
是UICollectionView吗？仔细看readme




------------------ 原始邮件 ------------------
发件人: "李哥"<notifications@github.com>;
发送时间: 2018年11月29日(星期四) 下午4:37
收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] cell上的按钮,如果是自定义按钮,比如调整UIEdgeInsets(图片在左，文字在右等)，会有问题 (#6)




能否加个属性和闪光模式一样,另外我提供的Demo如果不加闪光动画，布局没有错，加了动画就会出错，希望作者能指出问题所在，谢谢

**Comment by lzc1022** [comment]
tableView也是这样的

**Comment by tigerAndBull** [comment]
自定义按钮的问题我还没解决啊。。。




------------------ 原始邮件 ------------------
发件人: "李哥"<notifications@github.com>;
发送时间: 2018年11月29日(星期四) 下午5:10
收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] cell上的按钮,如果是自定义按钮,比如调整UIEdgeInsets(图片在左，文字在右等)，会有问题 (#6)




tableView也是这样的

**Comment by lzc1022** [comment]
最新的demo collectView布局错乱(直接下载，无修改
![11d2f6c5-e05f-4011-8ec9-b06933f6d84b](https://user-images.githubusercontent.com/9947322/49335031-b66fcf00-f61f-11e8-9777-7960be9df37f.png)
![130aa1d2-dfd2-4c47-b569-80a634cae090](https://user-images.githubusercontent.com/9947322/49335032-b8399280-f61f-11e8-9486-63c6c01a067d.png)

)

还有就是如果collectViewCell子控件去除动画类型的话，什么都不显示，但是列表cell去除的话可以,望修复
![35ec4adf-d575-4350-b308-41d0b055c28c](https://user-images.githubusercontent.com/9947322/49335045-21b9a100-f620-11e8-8522-f7f3b18e017c.png)

**Comment by lzc1022** [comment]
![1a41e257-b18d-4930-9a77-7200e36f97be](https://user-images.githubusercontent.com/9947322/49335273-757ab900-f625-11e8-8b05-98b3f9eb94e1.png)
我改了这段代码就可以了

**Comment by lzc1022** [comment]
![34c8c508-ae32-473a-9d22-4b17b77f8d48](https://user-images.githubusercontent.com/9947322/49349032-a0c3dd80-f6e3-11e8-91bc-77063284ab13.png)
![simulator screen shot - iphone x - 2018-12-03 at 10 06 34](https://user-images.githubusercontent.com/9947322/49349041-af11f980-f6e3-11e8-95c1-5a19cd23d961.png)
高度不确定出问题
