### ISSUE TITLE
两个问题~

### ISSUE THREAD

**Issue by OneKnife** [tigerAndBull/LoadAnimatedDemo-ios#7]
1.
[[TABViewAnimated sharedAnimated]initWithShimmerAnimated];
在appDelegate 中设置了动画类型后，所有view单独设置的superAnimationType都无效了。这个优先级是不是太高了。我认为在这里应该是设置一个默认动画类型。

2.
TABViewSuperAnimationTypeDefault
TABViewSuperAnimationTypeClassic
TABViewSuperAnimationTypeOnlySkeleton
这三种动画的效果看起来效果是一样的。是有什么区别么？

**Comment by OneKnife** [comment]
补充一下第二条，使用这种初始化方法后，三种动画是没有区别的。 [[TABViewAnimated sharedAnimated]initWithAnimatedDuration:0.6 withColor:tab_kBackColor];

**Comment by tigerAndBull** [comment]
> 补充一下第二条，使用这种初始化方法后，三种动画是没有区别的。 [[TABViewAnimated sharedAnimated]initWithAnimatedDuration:0.6 withColor:tab_kBackColor];

后面出个思维导图吧，到时候@你

**Comment by tigerAndBull** [comment]
> [[TABViewAnimated sharedAnimated]initWithShimmerAnimated];
> 在appDelegate 中设置了动画类型后，所有view单独设置的superAnimationType都无效了。这个优先级是不是太高了。我认为在这里应该是设置一个默认动画类型。
> 
> 
> TABViewSuperAnimationTypeDefault
> TABViewSuperAnimationTypeClassic
> TABViewSuperAnimationTypeOnlySkeleton
> 这三种动画的效果看起来效果是一样的。是有什么区别么？

思维导图已经更新了，最近比较忙，忘记回复你了

**Comment by OneKnife** [comment]
好的，谢谢了
