### ISSUE TITLE
使用闪光灯模式出现的问题

### ISSUE THREAD

**Issue by tanjieaa** [tigerAndBull/LoadAnimatedDemo-ios#9]
使用闪光灯模式，然后停止动画的时候，label的动画是正常的，但是闪光灯动画一直在；
我看更新记录，你说闪光灯模式所有子控件都会设置TABViewLoadAnimationWithOnlySkeleton，那TABViewLoadAnimationShort和TABViewLoadAnimationLong是不是会不起作用？我用了，这两种是起作用的，demo里闪光灯模式也是不起作用，不知什么原因

**Comment by tanjieaa** [comment]
原来是didFinishLaunchingWithOptions没设置

**Comment by tanjieaa** [comment]
不过我用
[[TABViewAnimated sharedAnimated]initWithAnimatedDuration:0.5 withColor:tab_kBackColor withLongToValue:1.5 withShortToValue:0.5];
还是出现，闪光灯不消失的问题

**Comment by tigerAndBull** [comment]
> 不过我用
> [[TABViewAnimated sharedAnimated]initWithAnimatedDuration:0.5 withColor:tab_kBackColor withLongToValue:1.5 withShortToValue:0.5];
> 还是出现，闪光灯不消失的问题

使用这个初始化方法，就没有闪光灯了，这个思维导图有说明，
当然在该初始化方法下，你使用闪光灯有效是我的问题，后面会做修改，
不好意思，最近比较忙，没时间看github
